Repository udistrital/arka_mid, pull requests merged in 2021-03, with the labels that each got.

#108 Refactorizada consulta de actas
  controllers/acta_recibido.go
  helpers/actaRecibido/actaRecibd.helper.go
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/actaRecibido/filtroActas.go
  helpers/proveedorHelper/poveedor.helper.go
  helpers/tercerosHelper/tercero.helper.go
  helpers/utilsHelper/utilsHelper.helper.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: desarrollo

#109 Contratistas ya no se traen de proveedores sino de terceros
  controllers/acta_recibido.go
  helpers/actaRecibido/actaRecibd.helper.go
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/actaRecibido/filtroActas.go
  helpers/proveedorHelper/poveedor.helper.go
  helpers/tercerosHelper/tercero.helper.go
  helpers/utilsHelper/utilsHelper.helper.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: desarrollo

#110 Feature/consecutivosplacas
  controllers/elemento.go
  helpers/actaRecibido/actaRecibdo.helper.go
  routers/router.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: desarrollo

#111 Captura de errores en carga masiva + elementos
  controllers/elemento.go
  helpers/actaRecibido/actaRecibdo.helper.go
  routers/router.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: desarrollo

#114 feat:Ajuste de la libreria auditoria
  main.go
Labels: desarrollo

#119 Auditoria + modelos de datos asociados a Oikos2, actualizados
  helpers/actaRecibido/actaRecibdo.helper.go
  main.go
  models/sede.go
  models/sede_dependencia.go
Labels: bug

#121 fix/UbicacionesGetAllActas
  helpers/actaRecibido/actaRecibd.helper.go
  models/acta_recibido.go
  models/asignaion_espacio_fisico_dependencia.go
  models/espacio_fisico.go
  models/sede.go
  models/sede_dependencia.go
  models/tipo_espacio.go
Labels: bug, desarrollo

#120 Feat/proveedores de terceros
  go.mod
  go.sum
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/actaRecibido/buffers.go
  helpers/tercerosHelper/proveedores.go
  helpers/tercerosHelper/tipoTercero.helper.go
Labels: desarrollo

#122 fix bugs modulo entradas/acta recibido + terceros Proveedores
  go.mod
  go.sum
  helpers/actaRecibido/actaRecibd.helper.go
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/actaRecibido/buffers.go
  helpers/tercerosHelper/proveedores.go
  helpers/tercerosHelper/tipoTercero.helper.go
  models/acta_recibido.go
  models/asignaion_espacio_fisico_dependencia.go
  models/espacio_fisico.go
  models/sede.go
  models/sede_dependencia.go
  models/tipo_espacio.go
Labels: bug, desarrollo

#118 fix:Arreglar función de capturar encargado de una placa
  controllers/entrada.go
  helpers/entradaHelper/entrada.helper.go
  helpers/tercerosHelper/tercero.helper.go
Labels: desarrollo

#123 Capturar tercero asignado a una placa
  controllers/entrada.go
  helpers/entradaHelper/entrada.helper.go
  helpers/tercerosHelper/tercero.helper.go
Labels: desarrollo

#125 Fix/actas proveedor
  helpers/actaRecibido/actaRecibdo.helper.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: bug, desarrollo, documentation

#128 fix: revision control de errores al obtener lista de actas #126
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/autenticacion/autenticacion.helper.go
Labels: bug

#130 fix: Arreglo funcion getContratista
  helpers/tercerosHelper/contratistas.go
Labels: bug

#131 fix de errores por roles y contratistas
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/autenticacion/autenticacion.helper.go
  helpers/tercerosHelper/contratistas.go
Labels: bug
