Repository udistrital/arka_mid, pull requests merged in 2021-04, with the labels that each got.

#132 Feat/anular entrada
  controllers/entrada.go
  helpers/entradaHelper/entrada.helper.go
  main.go
  routers/commentsRouter_controllers.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: desarrollo

#136 control de errores en actas/entradas/salidas
  controllers/entrada.go
  controllers/parametros.go
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/entradaHelper/entrada.helper.go
Labels: bug

#133 Fix/bodega consumo
  controllers/bodega_consumo.go
  controllers/terceros.go
  go.mod
  go.sum
  helpers/actaRecibido/buffers.go
  helpers/bajasHelper/bajasHelper.helper.go
  helpers/bodegaConsumoHelper/bodegaConsumo.helper.go
  helpers/bodegaConsumoHelper/buffers.go
  helpers/entradaHelper/entrada.helper.go
  helpers/tercerosHelper/tercero.helper.go
Labels: bug

#138 Fix/contratistas
  helpers/tercerosHelper/contratistas.go
Labels: bug

#139 Fix: consultar cuentas subgrupo
  controllers/catalogo_elementos.go
  helpers/catalogoElementosHelper/catalogoElementos.helper.go
  helpers/cuentasContablesHelper/cuentasContables.helper.go
  models/respuestas_APIs.go
  swagger/swagger.json
  swagger/swagger.yml
Labels: bug

#141 Fix/control errores
  controllers/acta_recibido.go
  controllers/bajas.go
  controllers/catalogo_elementos.go
  controllers/elemento.go
  controllers/entrada.go
  controllers/parametros.go
  controllers/salida.go
  controllers/terceros.go
  helpers/catalogoElementosHelper/catalogoElementos.helper.go
  helpers/tercerosHelper/contratistas.go
Labels: bug

#143 fix: .gitignore & go module updated
  .gitignore
  go.mod
  go.sum
Labels: bug

#147 test: agrega logs
  helpers/tercerosHelper/contratistas.go
Labels: bug

#149 Fix/misc test
  .drone.yml
  helpers/tercerosHelper/contratistas.go
  tests/helpers/actaRecibidoHelper/actaRecibido.helper_test.go
Labels: bug

#152 Fix/refactor: control de errores
  controllers/acta_recibido.go
  controllers/bajas.go
  controllers/catalogo_elementos.go
  controllers/elemento.go
  controllers/entrada.go
  controllers/parametros.go
  controllers/salida.go
  controllers/terceros.go
  helpers/actaRecibido/actaRecibdo.helper.go
  helpers/actaRecibido/buffers.go
  helpers/catalogoElementosHelper/catalogoElementos.helper.go
  helpers/entradaHelper/entrada.helper.go
  helpers/salidaHelper/salida.helepr.go
  helpers/tercerosHelper/tipoTercero.helper.go
  helpers/utilsHelper/utilsHelper.helper.go
Labels: desarrollo, enhancement

#153 Fix/bodega
  controllers/bodega_consumo.go
  helpers/bajasHelper/bajasHelper.helper.go
  helpers/bodegaConsumoHelper/bodegaConsumo.helper.go
Labels: bug
